services:
  # Database
  db:
    image: postgres:16
    container_name: db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Discovery Server
  eureka-server:
    build:
      context: ./backend/eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8761/eureka/apps"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "${KAFKA_PORT:-9092}:9092"
      - "${KAFKA_CONTROLLER_PORT:-9093}:9093"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:${KAFKA_CONTROLLER_PORT:-9093}"
      KAFKA_LISTENERS: PLAINTEXT://kafka:${KAFKA_PORT:-9092},CONTROLLER://kafka:${KAFKA_CONTROLLER_PORT:-9093}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_PORT:-9092}
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/var/lib/kafka/data
      - ./create-topics.sh:/create-topics.sh

  # API Gateway
  api-gateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "${GATEWAY_PORT:-8080}:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      eureka-server:
        condition: service_healthy

  # Microservices
  spotify-integration-service:
    build:
      context: ./backend/spotify-integration-service
      dockerfile: Dockerfile
    container_name: spotify-integration-service
    ports:
      - "${SPOTIFY_INTEGRATION_SERVICE_PORT:-8090}:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}
      SPOTIFY_API_BASE_URL: ${SPOTIFY_API_BASE_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SPRING_WEB_CORS_ALLOWED_ORIGINS: ${SPRING_WEB_CORS_ALLOWED_ORIGINS}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  album-service:
    build:
      context: ./backend/album-service
      dockerfile: Dockerfile
    container_name: album-service
    ports:
      - "${ALBUM_SERVICE_PORT:-8083}:8083"
    environment: &db-env
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  artist-service:
    build:
      context: ./backend/artist-service
      dockerfile: Dockerfile
    container_name: artist-service
    ports:
      - "${ARTIST_SERVICE_PORT:-8084}:8084"
    environment: *db-env
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  history-service:
    build:
      context: ./backend/history-service
      dockerfile: Dockerfile
    container_name: history-service
    ports:
      - "${HISTORY_SERVICE_PORT:-8085}:8085"
    environment: *db-env
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  listener-service:
    build:
      context: ./backend/listener-service
      dockerfile: Dockerfile
    container_name: listener-service
    ports:
      - "${LISTENER_SERVICE_PORT:-8086}:8086"
    environment: *db-env
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  playlist-service:
    build:
      context: ./backend/playlist-service
      dockerfile: Dockerfile
    container_name: playlist-service
    ports:
      - "${PLAYLIST_SERVICE_PORT:-8087}:8087"
    environment: *db-env
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  song-service:
    build:
      context: ./backend/song-service
      dockerfile: Dockerfile
    container_name: song-service
    ports:
      - "${SONG_SERVICE_PORT:-8088}:8088"
    environment: *db-env
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
  

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      FBFM_API_URL: ${VITE_API_URL}
    depends_on:
      api-gateway:
        condition: service_healthy

volumes:
  postgres-data: