version: "3.9"

services:
  # Database Service 
  db:
    image: postgres:16
    container_name: spotify_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./database/db/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # PgAdmin Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: spotify_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db

  # Backend Service
  backend:
    image: maven:3.9-eclipse-temurin-25
    container_name: spotify_backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - SPRING_WEB_CORS_ALLOWED_ORIGINS=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SPOTIFY_REDIRECT_URI=http://127.0.0.1:${BACKEND_PORT:-8080}/api/auth/callback
    command: mvn spring-boot:run
    depends_on:
      db:
        condition: service_healthy

  # Frontend Service
  frontend:
    image: node:20
    container_name: spotify_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_PORT=${FRONTEND_PORT:-3000}
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend

volumes:
  postgres_data:
