server:
  forward-headers-strategy: framework
  port: 8080

spring:
  application:
    name: api-gateway
  output:
    ansi:
      enabled: always

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route: /album/** -> album-service
            - id: album-route
              uri: lb://album-service
              predicates:
                - Path=/api/albums/**

            # Route: /artist/** -> artist-service
            - id: artist-route
              uri: lb://artist-service
              predicates:
                - Path=/api/artists/**

            # Route: /history/** -> history-service
            - id: history-route
              uri: lb://history-service
              predicates:
                - Path=/api/history/**

            # Route: /listener/** -> listener-service
            - id: listener-route
              uri: lb://listener-service
              predicates:
                - Path=/api/users/**

            # Route: /playlist/** -> playlist-service
            - id: playlist-route
              uri: lb://playlist-service
              predicates:
                - Path=/api/playlists/**

            # Route: /song/** -> song-service
            - id: song-route
              uri: lb://song-service
              predicates:
                - Path=/api/songs/**

            # Route: /spotify-integration/** -> spotify-integration-service
            - id: spotify-integration-route
              uri: lb://spotify-integration-service
              predicates:
                - Path=/api/auth/**

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Logging for debugging routes
logging:
  level:
    org.spring: DEBUG

# Actuator Config
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:averylongsecretkeythatissecureenoughforhmacsha256algorithm}
  expiration: ${JWT_EXPIRATION:86400000}