spring:
  application:
    name: logging-service
    port: 8090
  
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: logging-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    
eureka:
  client:
    fetch-registry: 'true'
    register-with-eureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: 'true'
